### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [alekseivoroshilov/learningjava3#1]
1. Словил исключение:
```
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 8
	at checkers.PlayCheckers.lambda$makeChecker$0(PlayCheckers.java:191)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
```
На таком ходу (на месте красных крестов были чёрыне шашки):
<img src="https://i.imgur.com/M8h0uzq.png"/>
2. Не проверяется правило обязательного взятия
3. В методе `makeChecker` пристутствует дублирование кода. Попробуйте обобщить код, например, добавив методы в шашку или тип шашки для определения направления хода.
4. Уберите отладочную печать на консоль, часть её совершенно бесполезна:
```
Checker@1ecd5a70 queen:false
Checker@53447020 queen:false
Checker@5eccb6a9 queen:false
Checker@586348ba queen:false
Checker@477c38b4 queen:false
Checker@153a9790 queen:false
Checker@59a6d418 queen:false
Checker@352f0ee8 queen:false
Checker@181bf38b queen:false
Checker@72644b36 queen:false
Checker@2282eabe queen:false
Checker@4ab26d13 queen:false
```

**Comment by alekseivoroshilov** [comment]
Ловил то же исключение, но после исправления и последующих тестов не поймал его. Сейчас всё до конца продумаю.

**Comment by alekseivoroshilov** [comment]
Исправлено

**Comment by alekseivoroshilov** [comment]
Исправлена проблема с обязательным поеданием шашек. Теперь алгоритм соблюдает все правила корректно.
